table Medidas
	lineageTag: b466fbcb-db65-49e5-bcbf-07e43d90655d

	measure 'Color_DIA 2026-1' = ```
			
			SWITCH(
			    SELECTEDVALUE('2026-1'[DIA]),
			    "lunes", "#2F5597",
			    "martes", "#548235",
			    "miercoles", "#BF9000",
			    "jueves", "#7030A0",
			    "viernes", "#1F6E8C",
			    "sabado", "#A5A5A5",
			    "domingo", "#7F0000"
			)
			
			```
		displayFolder: Color
		lineageTag: 54f3f087-3605-481c-bb45-1603e5206eab

	measure 'Color_DIA 2025-1' =
			
			SWITCH(
			    SELECTEDVALUE('DA002_2025-2'[DIA]),
			    "lunes", "#2F5597",
			    "martes", "#548235",
			    "miercoles", "#BF9000",
			    "jueves", "#7030A0",
			    "viernes", "#1F6E8C",
			    "sabado", "#A5A5A5",
			    "domingo", "#7F0000"
			)
		displayFolder: Color
		lineageTag: 1c0ad9c8-f69b-4af4-b0b4-9ca7304a86c1

	measure 'Cursos Sin Docente (Sin Duplicados)' = ```
			
			CALCULATE(
			    DISTINCTCOUNT('2026-1'[ID Programacion]),
			    FILTER(
			        '2026-1',
			        ISBLANK('2026-1'[ID DOCENTE])
			            || TRIM('2026-1'[ID DOCENTE]) = ""
			    )
			)
			
			```
		formatString: 0
		lineageTag: 61759d83-e45a-4256-8a31-9771d6e23417

	measure Medida
		lineageTag: eee37b51-995a-46c4-9662-800375db9751

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Promedio Horas 2026-1 M1+P' = ```
			
			AVERAGE(RUD[HORAS 26-1 M1+P])
			
			```
		displayFolder: RUD
		lineageTag: 17200f16-263c-4b03-9c67-055bd8cab3b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Horas 2026-1 M2+P' =
			
			AVERAGE(RUD[HORAS 26-1 M2+P])
		displayFolder: RUD
		lineageTag: 8471f65e-9047-4686-9faf-e240f1cf7e11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio REAL' = ```
			
			DIVIDE(
			    [Promedio Horas 2026-1 M2+P] +
			    [Promedio Horas 2026-1 M1+P],
			    2
			)
			
			```
		displayFolder: RUD
		lineageTag: 6924ced3-e8a0-48cd-864c-ba1309f4b975

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: 90a2f866-605e-44bd-ad3a-44aad2be37a8
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = d4916d719725416da61a49f6c957ab97

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

